/**
 * Generated by scripts/eac-vault-mint.mjs — do not edit by hand.
 * Seal material for the co-paid lane: two masked shards plus the GCM payload.
 * Readable form exists nowhere; see src/vault.js for the gate and the derivation.
 */

export const LANE_SHARDS = [
  {
    "s": "0kCrCLMaHxU8ym/LnyQMgOpm9XGvsN05",
    "w": "lbsMyyYlm1ulz1tFBtGsFw=="
  },
  {
    "s": "L5fyN/Qs+Lm4pqv9u3iu7it5wV+45m6e",
    "w": "TjIgRboPeIGNdbplqptMcQ=="
  }
]
export const LANE_SEAL = "V7D2T8Vp8D8YD3027nj6oxen8JLzacFoVzFnQtlKM8uReWwntauCkVTO/T96u7cvSKvpC0aWDcIJok1quYUN+4KyK0Ph24lLxcUHGLcYIbgjOCv2riqXP2rQQtVmmA54SbihHcmVyR8BLPLFUxoZQh3DQbI+iT3ARaKBynf5zcij+QHkHJbapwSdG3lK"
