/**
 * Generated by scripts/eac-vault-mint.mjs — do not edit by hand.
 * Anchor shard for the co-paid lane seal (its peers live in vault-data.js).
 */

export const LANE_ANCHOR = {
  "s": "I7tAAi5RjsdjuBLzQ6rBdrdIoVpDMxby",
  "w": "GuSR8yKw9Pl1NG52TeJ0zQ=="
}
