/**
 * Generated by scripts/eac-vault-mint.mjs — do not edit by hand.
 * Seal material for the co-paid lane: two masked shards plus the GCM payload.
 * Readable form exists nowhere; see src/vault.js for the gate and the derivation.
 */

export const LANE_SHARDS = [
  {
    "s": "hHguGHUHB/TZNTKh8iCjIniTHQY/6DKj",
    "w": "dSAWjHJ2NkV0/Fvuvx0apQ=="
  },
  {
    "s": "LABmpMgw0k3TC2yk2T+i7uNpooQgBbai",
    "w": "R3A6tnqDFqt9bnPnawfH3Q=="
  }
]
export const LANE_SEAL = "gidl4kpzRbo3fImfYo7wxnlvsv+m/QdMwCxOUtAEWhXMWFhTSKdKxlSzgMgG5i8+pdQhBd8Uo18rNOOBLa/6ZgGVvnJKhnm4X2eUmc5YbWDJqwOBF/z1eAYsf4tkHpDVbR7YZEDJGnMUlhNAluojnnDRp9JFNk1PnMDzDmcV1Dk3ARvMzTIvkOXd7ZvgY9yvlOCql4yw3NLWcw=="
