/**
 * Generated by scripts/eac-vault-mint.mjs — do not edit by hand.
 * Anchor shard for the co-paid lane seal (its peers live in vault-data.js).
 */

export const LANE_ANCHOR = {
  "s": "N2R2fzXcan2yaF6dva0cgXskNdopH2az",
  "w": "BXu65FctvmzSdhh46Tkugw=="
}
